config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :partners

end

app/models/partner.rb
class Partner < ActiveRecord::Base
  validates :nickname, presence: true, length: { minimum: 5 }
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def index
    @partners = Partner.all
  end

  def show
    @partner = Partner.find(params[:id])
  end

  def new
    @partner = Partner.new
  end

  def edit
    @partner = Partner.find(params[:id])
  end

  def create
    @partner = Partner.new(partner_params)

    if @partner.save
      redirect_to @partner
    else
      render 'new'
    end
  end

  def update
    @partner = Partner.find(params[:id])

    if @partner.update(partner_params)
      redirect_to @partner
    else
      render 'edit'
    end
  end

  def destroy
    @partner = Partner.find(params[:id])
    @partner.destroy

    redirect_to partners_path
  end

private

  def partner_params
    params.require(:partner).permit(:nickname, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoneyMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partners/_form.html.erb
<%= form_for @partner do |f| %>

  <% if @partner.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:
      </h2>
      <ul>
        <% @partner.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/partners/edit.html.erb
<h1>Editing partner</h1>

<%= render 'form' %>

<%= link_to 'Back', partners_path %>

app/views/partners/index.html.erb
<h1>Partners</h1>

<p><%= link_to 'New Partner', new_partner_path %></p>

<table>
  <tr>
    <th>Nickname</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>

  <% @partners.each do |partner| %>
    <tr>
      <td><%= partner.nickname %></td>
      <td><%= partner.email %></td>
      <td><%= link_to 'Show', partner_path(partner) %></td>
      <td><%= link_to 'Edit', edit_partner_path(partner) %></td>
      <td><%= link_to 'Destroy', partner_path(partner), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/partners/new.html.erb
<h1>New Partner</h1>

<%= render 'form' %>

<%= link_to 'Back', partners_path %>

app/views/partners/show.html.erb
<p>
  <strong>Nickname:</strong>
  <%= @partner.nickname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @partner.email %>
</p>

<%= link_to 'Edit', edit_partner_path(@partner) %> |
<%= link_to 'Back', partners_path %>

app/views/welcome/index.html.erb
<h1>Welcome to MoneyMaker!</h1>
<%= link_to 'Partners', controller: 'partners' %>